version: '3.9'

services:
  csvserver:
    build: .
    image: infracloudio/csvserver:1.0
    ports:
      - '9393:9300'
    environment:
      - CSVSERVER_BORDER=Orange
  prometheus:
    image: "prom/prometheus:v2.22.0"
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - 9090:9090


